import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "./fonts";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "HiringCopilot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-[#000000] text-white">
        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
